dataset:
  dataset_path: ./data/preprocessed/
  path_dataset_train_csv: train.csv
  path_dataset_val_csv: val.csv
  path_dataset_test_csv: test.csv
  batch_size: 32
  num_workers: 8
model:
  name_pretrained_model: resnet50
  saving_dir_experiments: ./results/resnet50/
  saving_dir_model: models
  load_checkpoint: 0
  num_classes: 4
  num_epoch: 4
  learning_rate: 0.001
  scheduler_step_size: 10
  scheduler_gamma: 0.1
  freeze_layers: 1
  epoch_start_unfreeze: 2
  #layer_start_unfreeze: 0
  n_nodes: 256
  dropout: 0.3
  do_train: 1
  do_test: 0
data:
  size: 224
  do_resize: 1
  normalization: imagenet
benchmark:
  power_mode: balanced
  powermizer: auto
  hdmi: gpu
  expo: 1
  fan3: 70
  gpu_orient: vertical
  pcie: 4-16x